/*
 * model
 *
 * API for interacting with model.
 *
 * API version: 0.0.1
 * Contact: contact@josehernandez.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smidgen

import (
	utils "smidgen-backend/go/utils"
)

type BusinessUnit struct {
	UnitId         int32  `json:"unit_id"`
	Name           string `json:"name"`
	PointOfContact string `json:"point_of_contact"`
	AddressLineOne string `json:"address_line_one"`
	AddressLineTwo string `json:"address_line_two"`
	State          string `json:"state"`
	City           string `json:"city"`
	Country        string `json:"country"`
}

func AssertBusinessUnitRequired(obj BusinessUnit) error {
	elements := map[string]interface{}{
		"name":             obj.Name,
		"point_of_contact": obj.PointOfContact,
		"address_line_one": obj.AddressLineOne,
		"address_line_two": obj.AddressLineTwo,
		"state":            obj.State,
		"city":             obj.City,
		"country":          obj.Country,
	}
	for name, el := range elements {
		if isZero := utils.IsZeroValue(el); isZero {
			return &utils.RequiredError{Field: name}
		}
	}

	return nil
}

func AssertBusinessUnitConstraints(obj BusinessUnit) error {
	return nil
}
