/*
 * model
 *
 * API for interacting with model.
 *
 * API version: 0.0.1
 * Contact: contact@josehernandez.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smidgen

import (
	"time"
	utils "smidgen-backend/go/utils"
)

type EquipmentAssignment struct {
	AssignmentId int32 `json:"assignment_id"`

	UserId int32 `json:"user_id"`

	EquipmentId int32 `json:"equipment_id"`

	DateOfAssignment time.Time `json:"date_of_assignment"`
}

func AssertEquipmentAssignmentRequired(obj EquipmentAssignment) error {
	elements := map[string]interface{}{
		"assignment_id":      obj.AssignmentId,
		"user_id":            obj.UserId,
		"equipment_id":       obj.EquipmentId,
		"date_of_assignment": obj.DateOfAssignment,
	}
	for name, el := range elements {
		if isZero := utils.IsZeroValue(el); isZero {
			return &utils.RequiredError{Field: name}
		}
	}

	return nil
}

func AssertEquipmentAssignmentConstraints(obj EquipmentAssignment) error {
	return nil
}
