/*
 * model
 *
 * API for interacting with model.
 *
 * API version: 0.0.1
 * Contact: contact@josehernandez.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smidgen

type HttpValidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}

// AssertHttpValidationErrorRequired checks if the required fields are not zero-ed
func AssertHttpValidationErrorRequired(obj HttpValidationError) error {
	for _, el := range obj.Detail {
		if err := AssertValidationErrorRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertHttpValidationErrorConstraints checks if the values respects the defined constraints
func AssertHttpValidationErrorConstraints(obj HttpValidationError) error {
	return nil
}
