/*
 * model
 *
 * API for interacting with model.
 *
 * API version: 0.0.1
 * Contact: contact@josehernandez.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smidgen

type LocationInner struct {
}

// AssertLocationInnerRequired checks if the required fields are not zero-ed
func AssertLocationInnerRequired(obj LocationInner) error {
	return nil
}

// AssertLocationInnerConstraints checks if the values respects the defined constraints
func AssertLocationInnerConstraints(obj LocationInner) error {
	return nil
}
