/*
 * api
 *
 * API for interacting with api.
 *
 * API version: 0.0.1
 * Contact: contact@josehernandez.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smidgen

import (
	"context"
	"errors"
	"net/http"
	api "smidgen-backend/go/api"
	models "smidgen-backend/go/models"
	utils "smidgen-backend/go/utils"
)

// BusinessUnitAPIService is a service that implements the logic for the BusinessUnitAPIServicer
// This service should implement the business logic for every endpoint for the BusinessUnitAPI API.
// Include any external packages or services that will be required by this service.
type BusinessUnitAPIService struct {
}

// NewBusinessUnitAPIService creates a default api service
func NewBusinessUnitAPIService() api.BusinessUnitAPIServicer {
	return &BusinessUnitAPIService{}
}

// AddUnitBusinessUnitPost - Create Business Unit
func (s *BusinessUnitAPIService) AddUnitBusinessUnitPost(ctx context.Context, businessUnit models.BusinessUnit) (utils.ImplResponse, error) {
	// TODO - update AddUnitBusinessUnitPost with the required logic for this service method.
	// Add api_business_unit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(202, interface{}{}) or use other options such as http.Ok ...
	// return utils.Response(202, interface{}{}), nil

	// TODO: Uncomment the next line to return response utils.Response(200, {}) or use other options such as http.Ok ...
	// return utils.Response(200, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(422, HttpValidationError{}) or use other options such as http.Ok ...
	// return utils.Response(422, HttpValidationError{}), nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("AddUnitBusinessUnitPost method not implemented")
}

// DeleteUnitBusinessUnitUnitIdDelete - Delete Business Unit
func (s *BusinessUnitAPIService) DeleteUnitBusinessUnitUnitIdDelete(ctx context.Context, unitId int32) (utils.ImplResponse, error) {
	// TODO - update DeleteUnitBusinessUnitUnitIdDelete with the required logic for this service method.
	// Add api_business_unit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(202, interface{}{}) or use other options such as http.Ok ...
	// return utils.Response(202, interface{}{}), nil

	// TODO: Uncomment the next line to return response utils.Response(200, {}) or use other options such as http.Ok ...
	// return utils.Response(200, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(422, HttpValidationError{}) or use other options such as http.Ok ...
	// return utils.Response(422, HttpValidationError{}), nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("DeleteUnitBusinessUnitUnitIdDelete method not implemented")
}

// GetUnitBusinessUnitGet - Get Business Units
func (s *BusinessUnitAPIService) GetUnitBusinessUnitGet(ctx context.Context) (utils.ImplResponse, error) {
	// TODO - update GetUnitBusinessUnitGet with the required logic for this service method.
	// Add api_business_unit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(200, []BusinessUnit{}) or use other options such as http.Ok ...
	// return utils.Response(200, []BusinessUnit{}), nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("GetUnitBusinessUnitGet method not implemented")
}

// GetUnitsBusinessUnitUnitIdGet - Get Business Unit
func (s *BusinessUnitAPIService) GetUnitsBusinessUnitUnitIdGet(ctx context.Context, unitId int32) (utils.ImplResponse, error) {
	// TODO - update GetUnitsBusinessUnitUnitIdGet with the required logic for this service method.
	// Add api_business_unit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(200, BusinessUnit{}) or use other options such as http.Ok ...
	// return utils.Response(200, BusinessUnit{}), nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(422, HttpValidationError{}) or use other options such as http.Ok ...
	// return utils.Response(422, HttpValidationError{}), nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("GetUnitsBusinessUnitUnitIdGet method not implemented")
}

// UpdateUnitBusinessUnitUnitIdPut - Update Business Unit
func (s *BusinessUnitAPIService) UpdateUnitBusinessUnitUnitIdPut(ctx context.Context, unitId int32, businessUnit models.BusinessUnit) (utils.ImplResponse, error) {
	// TODO - update UpdateUnitBusinessUnitUnitIdPut with the required logic for this service method.
	// Add api_business_unit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(202, interface{}{}) or use other options such as http.Ok ...
	// return utils.Response(202, interface{}{}), nil

	// TODO: Uncomment the next line to return response utils.Response(200, {}) or use other options such as http.Ok ...
	// return utils.Response(200, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(422, HttpValidationError{}) or use other options such as http.Ok ...
	// return utils.Response(422, HttpValidationError{}), nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("UpdateUnitBusinessUnitUnitIdPut method not implemented")
}
