/*
 * api
 *
 * API for interacting with api.
 *
 * API version: 0.0.1
 * Contact: contact@josehernandez.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smidgen

import (
	"context"
	"errors"
	"net/http"
	api "smidgen-backend/go/api"
	models "smidgen-backend/go/models"
	utils "smidgen-backend/go/utils"
)

// EquipmentAPIService is a service that implements the logic for the EquipmentAPIServicer
// This service should implement the business logic for every endpoint for the EquipmentAPI API.
// Include any external packages or services that will be required by this service.
type EquipmentAPIService struct {
}

// NewEquipmentAPIService creates a default api service
func NewEquipmentAPIService() api.EquipmentAPIServicer {
	return &EquipmentAPIService{}
}

// AddEquipmentEquipmentPost - Create equipment
func (s *EquipmentAPIService) AddEquipmentEquipmentPost(ctx context.Context, equipment models.Equipment) (utils.ImplResponse, error) {
	// TODO - update AddEquipmentEquipmentPost with the required logic for this service method.
	// Add api_equipment_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(202, interface{}{}) or use other options such as http.Ok ...
	// return utils.Response(202, interface{}{}), nil

	// TODO: Uncomment the next line to return response utils.Response(200, {}) or use other options such as http.Ok ...
	// return utils.Response(200, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(422, HttpValidationError{}) or use other options such as http.Ok ...
	// return utils.Response(422, HttpValidationError{}), nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("AddEquipmentEquipmentPost method not implemented")
}

// DeleteEquipmentEquipmentEquipmentIdDelete - Delete equipment
func (s *EquipmentAPIService) DeleteEquipmentEquipmentEquipmentIdDelete(ctx context.Context, equipmentId int32) (utils.ImplResponse, error) {
	// TODO - update DeleteEquipmentEquipmentEquipmentIdDelete with the required logic for this service method.
	// Add api_equipment_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(202, interface{}{}) or use other options such as http.Ok ...
	// return utils.Response(202, interface{}{}), nil

	// TODO: Uncomment the next line to return response utils.Response(200, {}) or use other options such as http.Ok ...
	// return utils.Response(200, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(422, HttpValidationError{}) or use other options such as http.Ok ...
	// return utils.Response(422, HttpValidationError{}), nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("DeleteEquipmentEquipmentEquipmentIdDelete method not implemented")
}

// GetEquipmentEquipmentGet - Get equipments
func (s *EquipmentAPIService) GetEquipmentEquipmentGet(ctx context.Context) (utils.ImplResponse, error) {
	// TODO - update GetEquipmentEquipmentGet with the required logic for this service method.
	// Add api_equipment_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(200, []Equipment{}) or use other options such as http.Ok ...
	// return utils.Response(200, []Equipment{}), nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("GetEquipmentEquipmentGet method not implemented")
}

// GetEquipmentsEquipmentEquipmentIdGet - Get equipment
func (s *EquipmentAPIService) GetEquipmentsEquipmentEquipmentIdGet(ctx context.Context, equipmentId int32) (utils.ImplResponse, error) {
	// TODO - update GetEquipmentsEquipmentEquipmentIdGet with the required logic for this service method.
	// Add api_equipment_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(200, Equipment{}) or use other options such as http.Ok ...
	// return utils.Response(200, Equipment{}), nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(422, HttpValidationError{}) or use other options such as http.Ok ...
	// return utils.Response(422, HttpValidationError{}), nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("GetEquipmentsEquipmentEquipmentIdGet method not implemented")
}

// UpdateEquipmentEquipmentEquipmentIdPut - Update equipment
func (s *EquipmentAPIService) UpdateEquipmentEquipmentEquipmentIdPut(ctx context.Context, equipmentId int32, equipment models.Equipment) (utils.ImplResponse, error) {
	// TODO - update UpdateEquipmentEquipmentEquipmentIdPut with the required logic for this service method.
	// Add api_equipment_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(202, interface{}{}) or use other options such as http.Ok ...
	// return utils.Response(202, interface{}{}), nil

	// TODO: Uncomment the next line to return response utils.Response(200, {}) or use other options such as http.Ok ...
	// return utils.Response(200, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(422, HttpValidationError{}) or use other options such as http.Ok ...
	// return utils.Response(422, HttpValidationError{}), nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("UpdateEquipmentEquipmentEquipmentIdPut method not implemented")
}
