/*
 * api
 *
 * API for interacting with api.
 *
 * API version: 0.0.1
 * Contact: contact@josehernandez.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smidgen

import (
	"context"
	"errors"
	"net/http"
	api "smidgen-backend/go/api"
	models "smidgen-backend/go/models"
	utils "smidgen-backend/go/utils"
)

// EquipmentAssignmentAPIService is a service that implements the logic for the EquipmentAssignmentAPIServicer
// This service should implement the business logic for every endpoint for the EquipmentAssignmentAPI API.
// Include any external packages or services that will be required by this service.
type EquipmentAssignmentAPIService struct {
}

// NewEquipmentAssignmentAPIService creates a default api service
func NewEquipmentAssignmentAPIService() api.EquipmentAssignmentAPIServicer {
	return &EquipmentAssignmentAPIService{}
}

// AddAssignmentEquipmentAssignmentPost - Create assignment
func (s *EquipmentAssignmentAPIService) AddAssignmentEquipmentAssignmentPost(ctx context.Context, equipmentAssignment models.EquipmentAssignment) (utils.ImplResponse, error) {
	// TODO - update AddAssignmentEquipmentAssignmentPost with the required logic for this service method.
	// Add api_equipment_assignment_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(202, interface{}{}) or use other options such as http.Ok ...
	// return utils.Response(202, interface{}{}), nil

	// TODO: Uncomment the next line to return response utils.Response(200, {}) or use other options such as http.Ok ...
	// return utils.Response(200, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(422, HttpValidationError{}) or use other options such as http.Ok ...
	// return utils.Response(422, HttpValidationError{}), nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("AddAssignmentEquipmentAssignmentPost method not implemented")
}

// DeleteAssignmentEquipmentAssignmentAssignmentIdDelete - Delete assignment
func (s *EquipmentAssignmentAPIService) DeleteAssignmentEquipmentAssignmentAssignmentIdDelete(ctx context.Context, assignmentId int32) (utils.ImplResponse, error) {
	// TODO - update DeleteAssignmentEquipmentAssignmentAssignmentIdDelete with the required logic for this service method.
	// Add api_equipment_assignment_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(202, interface{}{}) or use other options such as http.Ok ...
	// return utils.Response(202, interface{}{}), nil

	// TODO: Uncomment the next line to return response utils.Response(200, {}) or use other options such as http.Ok ...
	// return utils.Response(200, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(422, HttpValidationError{}) or use other options such as http.Ok ...
	// return utils.Response(422, HttpValidationError{}), nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("DeleteAssignmentEquipmentAssignmentAssignmentIdDelete method not implemented")
}

// GetAssignmentEquipmentAssignmentGet - Get assignments
func (s *EquipmentAssignmentAPIService) GetAssignmentEquipmentAssignmentGet(ctx context.Context) (utils.ImplResponse, error) {
	// TODO - update GetAssignmentEquipmentAssignmentGet with the required logic for this service method.
	// Add api_equipment_assignment_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(200, []EquipmentAssignment{}) or use other options such as http.Ok ...
	// return utils.Response(200, []EquipmentAssignment{}), nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("GetAssignmentEquipmentAssignmentGet method not implemented")
}

// GetAssignmentsEquipmentAssignmentAssignmentIdGet - Get assignment
func (s *EquipmentAssignmentAPIService) GetAssignmentsEquipmentAssignmentAssignmentIdGet(ctx context.Context, assignmentId int32) (utils.ImplResponse, error) {
	// TODO - update GetAssignmentsEquipmentAssignmentAssignmentIdGet with the required logic for this service method.
	// Add api_equipment_assignment_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(200, EquipmentAssignment{}) or use other options such as http.Ok ...
	// return utils.Response(200, EquipmentAssignment{}), nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(422, HttpValidationError{}) or use other options such as http.Ok ...
	// return utils.Response(422, HttpValidationError{}), nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("GetAssignmentsEquipmentAssignmentAssignmentIdGet method not implemented")
}

// UpdateAssignmentEquipmentAssignmentAssignmentIdPut - Update assignment
func (s *EquipmentAssignmentAPIService) UpdateAssignmentEquipmentAssignmentAssignmentIdPut(ctx context.Context, assignmentId int32, equipmentAssignment models.EquipmentAssignment) (utils.ImplResponse, error) {
	// TODO - update UpdateAssignmentEquipmentAssignmentAssignmentIdPut with the required logic for this service method.
	// Add api_equipment_assignment_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response utils.Response(202, interface{}{}) or use other options such as http.Ok ...
	// return utils.Response(202, interface{}{}), nil

	// TODO: Uncomment the next line to return response utils.Response(200, {}) or use other options such as http.Ok ...
	// return utils.Response(200, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(404, {}) or use other options such as http.Ok ...
	// return utils.Response(404, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(401, {}) or use other options such as http.Ok ...
	// return utils.Response(401, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(403, {}) or use other options such as http.Ok ...
	// return utils.Response(403, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(500, {}) or use other options such as http.Ok ...
	// return utils.Response(500, nil),nil

	// TODO: Uncomment the next line to return response utils.Response(422, HttpValidationError{}) or use other options such as http.Ok ...
	// return utils.Response(422, HttpValidationError{}), nil

	return utils.Response(http.StatusNotImplemented, nil), errors.New("UpdateAssignmentEquipmentAssignmentAssignmentIdPut method not implemented")
}
