// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://example.com/",
        "contact": {
            "name": "API Support",
            "url": "http://example.com/",
            "email": "support@example.com"
        },
        "license": {
            "name": "GPL-3",
            "url": "https://www.gnu.org/licenses/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck/": {
            "get": {
                "description": "See the current status of all Smidgen services",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "utilities"
                ],
                "summary": "Get a heart beat",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8050",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Smidgen Core API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
