basePath: /api/v1
host: localhost:8050
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://example.com/
  license:
    name: GPL-3
    url: https://www.gnu.org/licenses/
  termsOfService: http://example.com/
  title: Smidgen Core API
  version: "1.0"
paths:
  /healthcheck/:
    get:
      description: See the current status of all Smidgen services
      produces:
      - application/json
      responses: {}
      summary: Get a heart beat
      tags:
      - utilities
swagger: "2.0"
